module.exports = {
  TOKEN_SECRET: process.env.TOKEN_SECRET || 'aurelia_token',
  MONGO_URI: process.env.MONGO_URI || 'localhost:27017/recall',
  FACEBOOK_SECRET: process.env.FACEBOOK_SECRET || 'Facebook Client Secret',
  FOURSQUARE_SECRET: process.env.FOURSQUARE_SECRET || 'Foursquare Client Secret',
  GOOGLE_SECRET: process.env.OATH_CLIENT_SECRET,
  GITHUB_SECRET: process.env.GITHUB_SECRET || 'GitHub Client Secret',
  LINKEDIN_SECRET: process.env.LINKEDIN_SECRET || 'LinkedIn Client Secret',
  WINDOWS_LIVE_SECRET: process.env.WINDOWS_LIVE_SECRET || 'Windows Live Secret',
  TWITTER_KEY: process.env.TWITTER_KEY || 'Twitter Consumer Key',
  TWITTER_SECRET: process.env.TWITTER_SECRET || 'Twitter Consumer Secret',
  TWITTER_CALLBACK: process.env.TWITTER_CALLBACK || 'Twitter Callback URL',
  YAHOO_SECRET: process.env.YAHOO_SECRET || 'Yahoo Client Secret',
  DB: process.env.DB || 'dynamodb',
  DYNAMODB_ENDPOINT: 'http://localhost:8000',
//  DYNAMODB_ENDPOINT: 'dynamodb.us-east-1.amazonaws.com',
  DYNAMODB_ACCESSKYEID: process.env.ACCESS_KEY_ID,
  DYNAMODB_SECRETACCESKEY: process.env.SECRET_ACCESS_KEY,
  DYNAMODB_REGION: 'us-east-1',
  NEDB_USER_FILE: process.env.NEDB_USER_FILE || '/tmp/users.nedb',
  NEDB_NOTES_FILE: process.env.NEDB_NOTES_FILE || '/tmp/notes.nedb',
  gcloud: {  projectId: '...' },
};
